# # Build stage
# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# WORKDIR /src
# COPY . .
# RUN dotnet publish "Wasm-HotelManagementSystem.BlazorApp.csproj" -c Release -o /app/build

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
WORKDIR /src/Wasm-HotelManagementSystem.BlazorApp
RUN dotnet publish "Wasm-HotelManagementSystem.BlazorApp.csproj" -c Release -o /app/build



# Serve with nginx
FROM nginx:alpine AS final
COPY Wasm-HotelManagementSystem.BlazorApp/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build/wwwroot /usr/share/nginx/html
EXPOSE 80
