# # Base image with ASP.NET Core 8 runtime
# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
# WORKDIR /app
# EXPOSE 80

# # Build image with .NET 8 SDK
# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# WORKDIR /src
# COPY . .
# RUN dotnet publish "Wasm-HotelManagementSystem.BlazorApp.csproj" -c Release -o /app/out

# # Final stage
# FROM base AS final
# WORKDIR /app
# COPY --from=build /app/out .
# ENTRYPOINT ["dotnet", "Wasm-HotelManagementSystem.BlazorApp.dll"]


# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "Wasm-HotelManagementSystem.BlazorApp.csproj" -c Release -o /app/build

# Serve with nginx
FROM nginx:alpine AS final
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build/wwwroot /usr/share/nginx/html
EXPOSE 80
