name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100'

      - name: Build and publish Blazor WASM
        run: dotnet publish Wasm-HotelManagementSystem.BlazorApp/Wasm-HotelManagementSystem.BlazorApp.csproj -c Release -o publish

      - name: Copy wwwroot for nginx
        run: |
          mkdir deploy
          cp -r publish/wwwroot/* deploy/

      - name: Copy nginx.conf
        run: cp nginx.conf deploy/

      - name: Build Docker image
        run: docker build -t ${{ vars.DOCKER_USERNAME }}/hms-wasm:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/hms-wasm:latest

